version: '3.8'

services:
  server:
    container_name: hoyolab-nest-dev
    image: hoyolab-nest-dev:latest
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    volumes:
      - ../src:/app/src
      - ../docker/db:/app/db
      # - ../node_modules:/app/node_modules
    ports:
      - "2075:3000"
    # command: ["npm", "run", "start:dev"]
    command: npm run start:dev
