version: '3.8'

services:
  server:
    container_name: hoyolab-nest
    image: hoyolab-nest:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "2075:3000"
    # command: ["npm", "run", "start:dev"]
    command: npm run start:prod
